---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: release-<VERSION>-<Platform>-
  labels:
    app.kubernetes.io/product: crc
    app.kubernetes.io/ci: tekton
    tester: <tester>
spec:
  status: "PipelineRunPending"
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/crc-org/ci-definitions
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/crc-release-baremetal.yaml
  params:
  - name: crc-version
    value: '<VERSION>'
  - name: host-config-secret
    value: <tester>
  - name: downloadable-url
    value: <crcPath>
  - name: shasum-file
    value: <Shafile>
  - name: integration-timeout
    value: '120m'
  - name: s3-folder-path
    value: 'release/<VERSION>/ocp'
  - name: test-catelog
    value: "release-test"
  timeout: "5h"