---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: release-<VERSION>-<Platform>-
spec:
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/crc-org/ci-definitions
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/crc-release-virtual.yaml
  params:
  <plafrom-parameter> '<platform-version>'
  - name: crc-version
    value: "<VERSION>"
  - name: internal-base-url
    value: <crcPath>
  - name: internal-asset-name
    value: <crcName>
  - name: internal-shasum-name
    value: <Shafile>
  - name: shasum-file
    value: <Shafile>
  - name: s3-folder-path
    value: 'release/<VERSION>/ocp'
  - name: test-catelog
    value: "release-test"
  - name: run-integration
    value: "<integration>"
  - name: run-e2e
    value: "<e2e>"
  - name: e2e-tag
    value: "<e2etag>"
  timeout: "5h"