---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: crc-bundle-test-ocp-<B_VERSION>-rhel-arm64-
spec:
  pipelineRef:
    name: crc-qe-latest-arm64
  params:
    # - name: crc-scm-pr
    #   value: '4437'
    - name: bundle-base-url
      value: https://cdk-builds.usersys.redhat.com/builds/crc/bundles/openshift/<B_VERSION>-arm64/
    - name: bundle-name
      value: crc_libvirt_<B_VERSION>_arm64.crcbundle
    - name: bundle-shasumfile
      value: sha256sum.txt
    - name: e2e-tag
      value: "~@minimal && ~@story_microshift"
    - name: integration-tag
      value: "! microshift-preset"
    - name: s3-path
      value: nightly/crc/<B_VERSION>/rhel-9.4-arm64
    - name: test-catalog
      value: bundle-test
  workspaces:
    - name: storage 
      persistentVolumeClaim:
        claimName: pipelines-data
    - name: aws-credentials
      secret:
        secretName: aws-crcqe-bot
    - name: az-credentials
      secret:
        secretName: az-crcqe-bot
    - name: ocp-pullsecret
      secret:
        secretName: crc-crc-qe
    - name: s3-credentials
      secret:
        secretName: s3-aws-crcqe-asia
    - name: reportportal-credentials
      secret:
        secretName: reportportal-crc
  timeout: "5h"